[package]
name = "hash_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
chrono = "0.4.26"
sha256 = "1.4.0"
crossbeam-channel = "0.4.0"